# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankimage',
            name='file_format',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankimage',
            name='file_type',
            field=models.CharField(default=datetime.datetime(2016, 4, 13, 1, 14, 46, 181674, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankimage',
            name='metadata',
            field=models.CharField(default='', max_length=200),
        ),
    ]
