# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0003_remove_bankimage_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankimage',
            name='converted_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
